# --- !Ups

create table department (
  "id" bigint generated by default as IDENTITY(START WITH 1) NOT NULL PRIMARY KEY ,
  "name" VARCHAR(20) NOT NULL
);

create table user (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  department_id int not null
);

insert into department("id", "name") VALUES
  (1, "開発部"),
  (2, "営業部"),
  (3, "総務部");

insert into user("id", "name", department_id) VALUES
  (1, "Alice", 1),
  (2, "Bob", 2),
  (3, "Cathy", 3),
  (4, "Dick", 1),
  (5, "Elena", 2),
  (6, "Fineman", 3);

# --- !Downs

drop table user if exists;
drop table department if EXISTS ;
